##############################################################################
# Copyright (c) 2024, Oak Ridge National Laboratory                          #
# All rights reserved.                                                       #
#                                                                            #
# This file is part of RealTwin and is distributed under a __TBD__           #
# license. For the licensing terms see the LICENSE file in the top-level     #
# directory.                                                                 #
#                                                                            #
# Contributors (Add you name below to acknowledge your contribution):        #
# Xiangyong Roy Luo                                                          #
##############################################################################


# We will provide the default values for the configurations
# user can override these values by providing the same key and different values

input_dir: tools\ScenarioGenerator\datasets
Traffic:
    Volume: GridSmart_demand.csv
    TurningRatio: GridSmart_demand.csv
Network:
    NetworkName: chatt
    NetworkVertices: (-85.14977588011192, 35.040346288414916), (-85.15823020212477, 35.04345144844759), (-85.15829457513502, 35.043293338482925), (-85.14986171079225, 35.04018378032611)
    ElevationMap: chatt_elev.tif
Control:
    Signal: Synchro_signal.csv