# if true, the demo data will be used for the simulation, use default data: "chattanooga"
# or string of the name of the demo data, we provide a list of demo data ["chattanooga", "chicago", "nyc", "la", "sf", "dc"]
# For Dev, extend to retrieve the data from the db server.
demo_data: false

input_dir: C:\Users\xh8\ornl_work\github_workspace\Real-Twin-Dev\datasets\tss
output_dir:  # optional
Network:
    # the name of the network should not have space between words
    NetworkName: chatt
    # polygon points for the network in the format of (lon, lat)
    NetworkVertices: (-85.14977588011192, 35.040346288414916), (-85.15823020212477, 35.04345144844759), (-85.15829457513502, 35.043293338482925), (-85.14986171079225, 35.04018378032611)
Traffic: GridSmart
Control: Synchro_signal.csv
Calibration:
    # overall configuration for the calibration
    scenario_config:
        sim_start_time: 28800  # 8:00 AM In seconds
        sim_end_time: 32400  # 9:00 AM In seconds
        calibration_target:
            GEH: 5  # https://en.wikipedia.org/wiki/GEH_statistic
            GEHPercent: 0.85  # accepted match
        calibration_interval: 60  # mins
        demand_interval: 15  # mins
        calibration_time_step: 1
        calibration_seed: 42
        allow_u_turn: false  # if true, the u-turns are allowed in the simulation

        # Termination criteria for ga, sa and ts algorithms
        max_epoch: 1000  # max number of iterations
        max_fe: 10000  # max number of function evaluations
        max_time: 3600  # max time in seconds
        max_early_stop: 20  # max number of early stop iterations

    turn_inflow:
        initial_params: [0.5, 0.5, 0.5, 0.5, 0.5,
                         0.5, 0.5, 0.5, 0.5, 0.5,
                         0.5, 0.5, 100, 100, 100, 100]
        params_ranges: [[0, 1], [0, 1], [0, 1], [0, 1], [0, 1],
                        [0, 1], [0, 1], [0, 1], [0, 1], [0, 1],
                        [0, 1], [0, 1], [50, 200], [50, 200], [50, 200], [50, 200]]
        max_inflow: 200  # max inflow for the turning ratio

    behavior:
        initial_params:
            min_gap: 2.5  # min gap between vehicles in meters
            acceleration: 2.6  #  max acceleration in m/s^2
            deceleration: 4.5  # max deceleration in m/s^2
            sigma: 0.5  # driver imperfection
            tau: 1.00  # desired headway
            emergencyDecel: 9.0  # emergency deceleration in m/s^2
        params_ranges:
            min_gap: [1.0, 3.0]
            acceleration: [2.5, 3.0]
            deceleration: [4.0, 5.3]
            sigma: [0.0, 1.0]
            tau: [0.25, 1.25]
            emergencyDecel: [5.0, 9.3]

        # behavior calibration shared by all algorithms
        EB_tt: 240  # sec
        WB_tt: 180  # sec
        EB_edge_list: ["-312", "-293", "-297", "-288", "-286",
                        "-302", "-3221", "-322", "-313", "-284",
                        "-328", "-304"]
        WB_edge_list: ["-2801", "-280", "-307", "-327", "-281",
                        "-315", "-321", "-300", "-2851", "-285",
                        "-290", "-298", "-295"]

    ga_config:  # generic algorithm configuration
        epoch: 10  # number of generations
        pop_size: 8  # population size >=5
        pc: 0.75  # crossover probability
        pm: 0.1  # mutation probability
        model_selection: "BaseGA"  #  BaseGA, EliteSingleGA, EliteMultiGA, MultiGA, SingleGA

    sa_config:  # simulated annealing configuration
        # the original configuration for the Simulated Annealing
        num_variables: 16
        num_turning_ratio: 12  # remaining should be inflow
        initial_temperature: 100
        ubc: 200  # upper bound of inflow
        cost_difference: 2
        accept_prob: 0.5
        stopping_temperature: 0.001

        # new configuration for the Simulated Annealing
        epoch: 1000  # number of generations
        temp_init: 100  # initial temperature
        cooling_rate: 0.891  # same as previous
        scale: 0.1  # scale for the temperature
        model_selection: "OriginalSA"  # OriginalSA, GaussianSA, SwarmSA

    ts_config:  # tabu search configuration
        # the original configuration for the Tabu Search
        iterations: 3
        # tabu_size: 120
        neighborhood_size: 32
        move_range: 0.5   # initial move range
        num_turning_ratio: 12
        max_no_improvement_local: 5
        max_no_improvement_global: 30
        lower_bound: 0
        upper_bound: 1
        lbc: 0  # lower bound for inflow counts
        ubc: 200  # upper bound for inflow counts

        # new configuration for the Tabu Search
        epoch: 1000  # number of generations
        tabu_size: 10  # size of the tabu list;
        neighbour_size: 10  # size of the neighbourhood for generating candidate solutions
        perturbation_scale: 0.05  # scale of perturbation for the solution
