name: Build-wheels

on: [push, pull_request, workflow_dispatch]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # macos-13 is an intel runner, macos-14 is apple silicon
        os: [ubuntu-latest, windows-latest, macos-13, macos-14] # macos-14

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Build wheels
        run: |
          pip install build pyufunc grid2demand
          pip install utdf2gmns exceltomysql exceltosqlserver exceltopostgresql
          python -m build --outdir dist
          # python3 -m build --outdir dist

      - name: build-sdist
        run: |
          pipx run build --sdist

      - uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: |
            dist/*.tar.gz
            dist/*.whl
